apiVersion: v1
kind: Service
metadata:
  name: crms-frontend
  labels:
    app: crms-frontend
spec:
  selector:
    app: crms-frontend
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP
